version: "3.7"
name: verify-marktstammdaten

services:
  postgis-database:
      image: postgis/postgis:15-3.3
      container_name: postgis-database
      ports:
        - '5512:5432' #host:container
      environment:
        POSTGRES_DB: verify-marktstammdatenregister
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      volumes:
        - verifyMarktstammdatenDatabaseVolume:/var/lib/postgresql/data

volumes:
  verifyMarktstammdatenDatabaseVolume: